baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Siddharth Tewari'
theme = 'typo'

[taxonomies]
tag = 'tags'

[markup.goldmark.renderer]
unsafe= true

[params]
# Meta description
description = "Internet Home"
showFooter = false

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I’m Siddharth! I build things. I’m an Engineer, writer(when I feel like it), and in general, someone who likes to constantly learn.
I am deeply passionate about systems and networks engineering, if you'd like to talk please reach out to me!
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'tech'

# Lists parameters
paginationSize = 10
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "twitter"
url = "https://twitter.com/sidT_008"

[[params.social]]
name = "github"
url = "https://github.com/sid-008"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/siddharth-tewari-40a758221/"

[[params.social]]
name = "email"
url = "mailto:siddharthtewari14@gmail.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "linkstash"
url = "/linkstash"

[[params.menu]]
name = "tech"
url = "/tech"

[[params.menu]]
name = "articles"
url = "/articles"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'base16-snazzy'
